language: bash


services:
  - docker
  
script:
  - docker build --tag=my-application .
  - chmod +x ./deploy.sh


deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./deploy.sh
  on:
    tags: true
