sudo: required
language: bash
services:
  - docker
script:
  - docker build --tag=my-application .
  - docker build -t=my-application .
  - chmod +x ./deploy.sh
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
     tags: true
    

