language: bash
sudo: required

services:
  - docker

script:
  - docker build --tag=my-application .

deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./deploy.sh
  on:
    tags: true
    

