sudo: required
language: bash

services:
  - docker
  
before_script:
- docker-compose build AdForm

script:
 - >
    docker-compose run
    --rm
    
after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
