sudo: required
language: bash
services:
  - docker
before_script:
- docker-compose build adform
script: docker-compose run --rm --entrypoint sh -e KBC_DATA_DIR=/code/tests/data/
  - docker build --tag=my-application .
  - docker build -t=my-application .
  
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh" 
  on:
     tags: true
    

