language: bash


services:
  - docker
  
script:
  - docker build --tag=my-application .
  
after_success:
- docker images

deploy:
  provider: script
  skip_cleanup: true
  script: sh $TRAVIS_BUILD_DIR/deploy/deploy.sh
  on:
    tags: true
